-- Ringback — Supabase Postgres schema (Cycle 1 MVP)
-- Owner: Product Architect Agent + Engineering Agent
--
-- Apply this file once per environment via `supabase db push` or a SQL
-- migration runner. Apply `rls-policies.sql` afterwards.
--
-- Conventions:
--   - Every tenant-scoped table has a non-null tenant_id uuid FK.
--   - Timestamps are timestamptz.
--   - IDs are uuid generated by gen_random_uuid().
--   - We never DELETE; we soft-delete via deleted_at where it matters.

create extension if not exists "pgcrypto";
create extension if not exists "citext";

-- ─────────────────────────────────────────────────────────────────────
-- Tenants and platform admins
-- ─────────────────────────────────────────────────────────────────────

create table if not exists tenants (
    id              uuid primary key default gen_random_uuid(),
    name            text not null,
    brand           text not null,
    billing_email   citext not null,
    plan            text not null default 'tier_1'
                    check (plan in ('tier_1','tier_2','tier_3','trialing','canceled')),
    trial_ends_at   timestamptz,
    timezone        text not null default 'America/Chicago',
    locale          text not null default 'en-US',
    created_at      timestamptz not null default now(),
    deleted_at      timestamptz
);

create table if not exists platform_admins (
    auth_user_id    uuid primary key,
    email           citext not null unique,
    created_at      timestamptz not null default now()
);

create table if not exists users (
    id              uuid primary key default gen_random_uuid(),
    tenant_id       uuid not null references tenants(id) on delete restrict,
    auth_user_id    uuid unique,
    email           citext not null,
    role            text not null default 'dispatcher'
                    check (role in ('owner','dispatcher')),
    created_at      timestamptz not null default now(),
    unique (tenant_id, email)
);

-- ─────────────────────────────────────────────────────────────────────
-- Tenant configuration
-- ─────────────────────────────────────────────────────────────────────

create table if not exists phone_numbers (
    id              uuid primary key default gen_random_uuid(),
    tenant_id       uuid not null references tenants(id) on delete restrict,
    twilio_sid      text not null unique,
    e164            text not null unique,
    area_code       text,
    status          text not null default 'active'
                    check (status in ('pending','active','released')),
    created_at      timestamptz not null default now()
);

create table if not exists business_hours (
    tenant_id       uuid not null references tenants(id) on delete restrict,
    day_of_week     smallint not null check (day_of_week between 0 and 6),
    open_local      time not null,
    close_local     time not null,
    primary key (tenant_id, day_of_week)
);

create table if not exists service_zips (
    tenant_id       uuid not null references tenants(id) on delete restrict,
    zip             text not null,
    primary key (tenant_id, zip)
);

create table if not exists job_types (
    id                  uuid primary key default gen_random_uuid(),
    tenant_id           uuid not null references tenants(id) on delete restrict,
    label               text not null,
    avg_ticket_cents    integer not null default 0 check (avg_ticket_cents >= 0),
    emergency_keywords  text[] not null default '{}',
    is_emergency_default boolean not null default false,
    created_at          timestamptz not null default now(),
    unique (tenant_id, label)
);

-- ─────────────────────────────────────────────────────────────────────
-- Operational data
-- ─────────────────────────────────────────────────────────────────────

create table if not exists customers (
    id              uuid primary key default gen_random_uuid(),
    tenant_id       uuid not null references tenants(id) on delete restrict,
    name            text,
    phone_e164      text not null,
    address         text,
    zip             text,
    source          text default 'inbound_call',
    created_at      timestamptz not null default now(),
    unique (tenant_id, phone_e164)
);

create table if not exists calls (
    id                  uuid primary key default gen_random_uuid(),
    tenant_id           uuid not null references tenants(id) on delete restrict,
    twilio_call_sid     text not null unique,
    from_e164           text not null,
    to_e164             text not null,
    started_at          timestamptz not null default now(),
    ended_at            timestamptz,
    status              text not null default 'in_progress'
                        check (status in ('in_progress','answered','qualified','lost','emergency_routed','completed','failed')),
    recording_url       text,
    transcript_jsonb    jsonb not null default '[]'::jsonb
);
create index if not exists calls_tenant_started_idx on calls (tenant_id, started_at desc);

create table if not exists messages (
    id                  uuid primary key default gen_random_uuid(),
    tenant_id           uuid not null references tenants(id) on delete restrict,
    call_id             uuid references calls(id),
    customer_id         uuid references customers(id),
    direction           text not null check (direction in ('inbound','outbound')),
    twilio_message_sid  text unique,
    body                text not null,
    status              text not null default 'queued'
                        check (status in ('queued','sent','delivered','undelivered','failed','received')),
    created_at          timestamptz not null default now()
);
create index if not exists messages_tenant_created_idx on messages (tenant_id, created_at desc);

create table if not exists bookings (
    id                  uuid primary key default gen_random_uuid(),
    tenant_id           uuid not null references tenants(id) on delete restrict,
    customer_id         uuid not null references customers(id),
    call_id             uuid references calls(id),
    job_type_id         uuid references job_types(id),
    scheduled_for       timestamptz not null,
    duration_minutes    integer not null default 60 check (duration_minutes between 15 and 480),
    status              text not null default 'booked'
                        check (status in ('booked','rescheduled','canceled','completed','no_show')),
    gcal_event_id       text,
    notes               text,
    success_fee_charged boolean not null default false,
    created_at          timestamptz not null default now(),
    unique (tenant_id, customer_id, scheduled_for)  -- idempotency
);
create index if not exists bookings_tenant_sched_idx on bookings (tenant_id, scheduled_for);

create table if not exists digests (
    id              uuid primary key default gen_random_uuid(),
    tenant_id       uuid not null references tenants(id) on delete restrict,
    period_start    timestamptz not null,
    period_end      timestamptz not null,
    payload_jsonb   jsonb not null,
    sent_at         timestamptz,
    created_at      timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────
-- Audit log
-- ─────────────────────────────────────────────────────────────────────

create table if not exists events (
    id              bigserial primary key,
    tenant_id       uuid references tenants(id) on delete restrict,
    actor           text not null check (actor in ('agent','human','system','platform_admin')),
    kind            text not null,
    payload_jsonb   jsonb not null default '{}'::jsonb,
    created_at      timestamptz not null default now()
);
create index if not exists events_tenant_created_idx on events (tenant_id, created_at desc);
create index if not exists events_kind_idx on events (kind);

-- ─────────────────────────────────────────────────────────────────────
-- Billing
-- ─────────────────────────────────────────────────────────────────────

create table if not exists subscriptions (
    id                      uuid primary key default gen_random_uuid(),
    tenant_id               uuid not null unique references tenants(id) on delete restrict,
    stripe_customer_id      text not null unique,
    stripe_subscription_id  text unique,
    plan                    text not null check (plan in ('tier_1','tier_2','tier_3')),
    status                  text not null check (status in ('trialing','active','past_due','canceled','incomplete')),
    trial_ends_at           timestamptz,
    current_period_end      timestamptz,
    created_at              timestamptz not null default now(),
    updated_at              timestamptz not null default now()
);

create table if not exists usage_records (
    id                  uuid primary key default gen_random_uuid(),
    tenant_id           uuid not null references tenants(id) on delete restrict,
    booking_id          uuid references bookings(id),
    kind                text not null check (kind in ('booked_job','minute')),
    qty                 integer not null check (qty > 0),
    stripe_record_id    text unique,
    billed_at           timestamptz,
    created_at          timestamptz not null default now()
);
create index if not exists usage_records_tenant_idx on usage_records (tenant_id, created_at desc);

-- ─────────────────────────────────────────────────────────────────────
-- updated_at triggers (lightweight)
-- ─────────────────────────────────────────────────────────────────────

create or replace function set_updated_at() returns trigger
language plpgsql as $$
begin
    new.updated_at := now();
    return new;
end $$;

drop trigger if exists subscriptions_set_updated_at on subscriptions;
create trigger subscriptions_set_updated_at
    before update on subscriptions
    for each row execute function set_updated_at();
